### ISSUE TITLE
点击其它区域popup不消失

### ISSUE THREAD

**Issue by roodkcab** [vczh-libraries/gGac#21]

**Comment by vczh** [comment]
Windows下曾经用这个做法，但是后来发现还是有很多细小的bug。最后我找到了一个标准做法，就是监听整个进程的unactivated事件，以及每一个窗口的activated事件。进程的unactivated事件发生了就把全部popup关掉。每一个窗口的activated事件发生了就看要关掉哪一部分。

**Comment by roodkcab** [comment]
改为标准做法
