### ISSUE TITLE
系统的窗口边框需要处理

### ISSUE THREAD

**Issue by vczh** [vczh-libraries/gGac#6]
- 皮肤有“带系统边框”和“不带系统边框”两种模式
- 窗口缩放的时候需要收到根节点`GuiWindowComposition`的大小限制

**Comment by vczh** [comment]
![](https://github.com/vczh-libraries/Release/blob/master/Tutorial/GacUI_ControlTemplate/WindowSkin/Screenshot.gif?raw=true)

**Comment by roodkcab** [comment]
应该和 #7 一起做

**Comment by vczh** [comment]
其实不需要跟#7一起做。这个Windows皮肤的问题只是上面三个按钮的图标不对而已，功能上并没有问题。
